project:
  type: website
  output-dir: docs

website:
  title: "posit::conf(2025)"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: R/Pharma Summit
        href: rPharma.qmd
      - text: Pharmaverse
        href: pharmaverse.qmd
      - text: Wednesday Notes
        href: wednesday.qmd
      - text: Thursday Notes
        href: thursday.qmd
      - text: Pictures
        href: photos.qmd

format:
  html:
    toc: true
    toc-location: left
    toc-expand: true
    toc-depth: 4
    number-sections: false
    embed-resources: true
    code-background: true
    code-fold: true
    theme: zephyr
    grid:
      sidebar-width: 350px
      body-width: 1200px
      margin-width: 50px
      gutter-width: 1.5rem

execute:
  echo: true
  message: false
  warning: false
  output: asis

editor: source
